name: Changelog

on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    uses: vindicta-platform/.github/.github/workflows/changelog-template.yml@1216e0609ec638b935e0f4123b2f9fcc69cfe14f # main
    permissions:
      contents: write
