name: Commit Lint

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    uses: vindicta-platform/.github/.github/workflows/commit-lint-template.yml@1216e0609ec638b935e0f4123b2f9fcc69cfe14f # main
    permissions:
      contents: read
