name: Deprecation Tracker

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  scan:
    uses: vindicta-platform/.github/.github/workflows/deprecation-tracker-template.yml@1216e0609ec638b935e0f4123b2f9fcc69cfe14f # main
    permissions:
      contents: read
