name: Docs Build

on:
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  workflow_dispatch:

jobs:
  verify:
    uses: vindicta-platform/.github/.github/workflows/docs-build-template.yml@1216e0609ec638b935e0f4123b2f9fcc69cfe14f # main
    permissions:
      contents: read
