name: License Header Check

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**/*.py'
  workflow_dispatch:

jobs:
  check:
    uses: vindicta-platform/.github/.github/workflows/license-header-template.yml@1216e0609ec638b935e0f4123b2f9fcc69cfe14f # main
    permissions:
      contents: read
