name: Package Size

on:
  pull_request:
    branches: [main]
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  monitor:
    uses: vindicta-platform/.github/.github/workflows/package-size-template.yml@1216e0609ec638b935e0f4123b2f9fcc69cfe14f # main
    permissions:
      contents: read
