name: PR Quality Guard

on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize, reopened]

jobs:
  guard:
    uses: vindicta-platform/.github/.github/workflows/pr-guard-template.yml@1216e0609ec638b935e0f4123b2f9fcc69cfe14f # main
    permissions:
      contents: read
      pull-requests: write
