name: README Badges

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  badges:
    uses: vindicta-platform/.github/.github/workflows/readme-badges-template.yml@1216e0609ec638b935e0f4123b2f9fcc69cfe14f # main
    permissions:
      contents: write
